<a href="https://colab.research.google.com/github/ja-nana/Linear-Algebra_ChE_2nd-Sem-2021/blob/main/Assignment3_Siena_Vertudes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LABORATORY 4: **MATRICES**
---
##Objectives

At the end of this activity, we have been able to:


1. *Be familiar with matrices and their relation to linear equation.*

2. *Perform basic matrix operations.*

3. *Program and translate matrix equations and operations using Python.*





##Discussion


```
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

```




---
###**MATRICES**

rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns, which is used to represent a mathematical object or a property of such an object.



---
###Example **X** and **Y** as system of equation

$$
X = \left\{
    \begin{array}\
      a + b \\
      5a - 15b
    \end{array}
\right.\\
Y = \left\{
    \begin{array}\
      a+b+c \\
      2a - 3b -c \\
      =a + 5b + 7c
    \end{array}
\right. \\
Z = \left\{
    \begin{array}\
      q-2a+6b-10c \\
      4q- a -4b + c \\
      6q -a + 8b - 9c
    \end{array}
  \right. $$

####**"X"** is a system of 2 equations with 2 paramenters; 
####**"Y"** is a system of 3 equations with 3 parameters. Therefore, we can represent as matrices below:

$$
X=\begin{bmatrix} 3 & 5 \\ 8 & (-11)\end{bmatrix} \\
Y=\begin{bmatrix} 5 & 5 & 5 \\ 9 & -4 & 3 \\ -3 & 5 & 8\end{bmatrix} \\
Z=\begin{bmatrix} 3 & 3 & 9 &5 \\ 10 & -8 & 3 & -6 \\ 3 & -5 & -1 & 2\end{bmatrix}$$

###*Declaring Matrices*

> Definition or whatever emz


In [ ]:
##Function

def des_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:{matrix.shape}\nRank:{matrix.ndim}\n')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
## Declaring a 2 x 2 matrix
S = np.array([
    [4, 15],
    [17, 20]
])
des_mat(S)

Matrix:
[[ 4 15]
 [17 20]]

Shape:(2, 2)
Rank:2



In [ ]:
H = np.array([
    [8,-5],
    [9,4]
])
des_mat(H)

Matrix:
[[ 8 -5]
 [ 9  4]]

Shape:(2, 2)
Rank:2



In [ ]:
## Declaring a 3 x 2 matrix
E = np.array([
    [12, 7],
    [15, 26],
    [69, 15]
])
des_mat(E)

Matrix:
[[12  7]
 [15 26]
 [69 15]]

Shape:(3, 2)
Rank:2



In [ ]:
T = np.array([6,9,15,32,20])
des_mat(T)

Matrix:
[ 6  9 15 32 20]

Shape:(5,)
Rank:1



#Categorizing Matrices
---
There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values.
---



---
##According to Shape

###**Row and Column Matrices**
Row and column matrices are common in vector and matrix computations.

---

In [ ]:
##Declaring a ROW MATRIX

row_1D = np.array([ 5, 6, 7])
##Row 1 is a 1-D matrix with a shape of (3,), not really a matirx
row_2D = np.array([[ 4, 3, 5 ]])
##Row 2 is a 2-D matrix with a shape of (1,3)
des_mat(row_1D)
des_mat(row_2D)

Matrix:
[5 6 7]

Shape:(3,)
Rank:1

Matrix:
[[4 3 5]]

Shape:(1, 3)
Rank:2



In [ ]:
##Declaring Column Matrix

col_m = np.array ([ [11], [66], [45]])
##2-D matrix with a shape of (3,1)
des_mat(col_m)

Matrix:
[[11]
 [66]
 [45]]

Shape:(3, 1)
Rank:2



---
##Square Matrices

These are matrices with the same row an column sizes. eme

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape: {matrix.shape}\nRank:{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
sq_mat = np.array([
  [22, 34, 50], 
  [60, 89 ,99], 
  [10, 20, 30]
])

not_sq = np.array([
      [1,5,8], 
      [7,9,0]
])
describe_mat(sq_mat)
describe_mat(not_sq)

Matrix:
[[22 34 50]
 [60 89 99]
 [10 20 30]]

Shape: (3, 3)
Rank:2
Is Square: True

Matrix:
[[1 5 8]
 [7 9 0]]

Shape: (2, 3)
Rank:2
Is Square: False



---
##According to Element Values
---
###**Null Matrix**

A null matrix has no elements. It is a subspace of any vector or matrix
---

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:{matrix.shape}\nRank:{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_m = np.array([])
describe_mat(null_m)

Matrix is Null


---
###**Zero Matrix**
Can be any rectangular matric but the elements have a value of 0


In [ ]:
zero_row = np.zeros((4,5))
zero_sqr = np.zeros((8,9))
zero_rct = np.zeros((3,3))

print(f'Zero Row Matrix: \n{zero_row}')
print(f'Zero Square Matric: \n{zero_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Zero Square Matric: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
###**Ones Matrix**
The same as zero matrix which can be any rectangular matrix but all elements are 1s.

In [ ]:
one_row = np.ones((3,3))
one_sqr = np.ones((4,5))
one_rct = np.ones((6,6))

print(f'One Row Matrix: \n{one_row}')
print(f'One Square Matrix: \n{one_sqr}')
print(f'One Rectangular Matrix: \n{one_rct}')

One Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
One Square Matrix: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
One Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


---
##**Diagonal Matrix**
A square matric that the values are only at the diagonal of the matrix.


In [ ]:
np.array([[5,0,0], [0,5,0],[0,0,5]])

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [ ]:
q = np.diag([4, 3, 5, 6])
np.diag(q).shape == q.shape[0] == q.shape[1]

False

---
##**Identity Matrix**
A special diagonal matrix which the values at the diagonal are 1s.


In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

---
##**Upper Triangular Matrix**
It's a matrix that has no values below the diagonal.

In [ ]:
np.array([ [3,2,1], [0,6,5], [0,0,8]
])

array([[3, 2, 1],
       [0, 6, 5],
       [0, 0, 8]])

---
##**Lower Triangular Matrix**
Has no value above the diagonal

In [ ]:
np.array([[3,0,0],[4,8,0],[1,2,3]])

array([[3, 0, 0],
       [4, 8, 0],
       [1, 2, 3]])

---
#*Practice*


1.
 $$
\theta = 5x + 3y -z
$$


2.

$$
A = \left\{
    \begin{array}\
      x_1 + 2x_2 +x_3 \\
      4x_2 = x_3 \\
      10x_3
    \end{array}
  \right.
$$

3. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

---
#MATRIX ALGEBRA


##**Addition**

In [ ]:
X = np.array([ [1,1],[2,2],[4,4]])
Y = np.array([[3,3],[5,5],[7,7]])
X+Y

array([[ 4,  4],
       [ 7,  7],
       [11, 11]])

In [ ]:
2+X

array([[3, 3],
       [4, 4],
       [6, 6]])

##**Subtraction**

In [ ]:
X-Y

array([[-2, -2],
       [-3, -3],
       [-3, -3]])

In [ ]:
4-Y == 4*np.ones(Y.shape)-Y

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

##**Element-wise Multiplication**

In [ ]:
X*Y
np.multiply(X,Y)

array([[ 3,  3],
       [10, 10],
       [28, 28]])

In [ ]:
5*Y

array([[15, 15],
       [25, 25],
       [35, 35]])

In [ ]:
X@Y

##cannot be with the given matix

ValueError: ignored

In [ ]:
alpha=5**-5
X/(alpha+Y)

array([[0.33329778, 0.33329778],
       [0.3999744 , 0.3999744 ],
       [0.57140245, 0.57140245]])

In [ ]:
np.add(X,Y)

array([[ 4,  4],
       [ 7,  7],
       [11, 11]])

#***TASK 1***
Create a function ``` mat_desc() ``` that describes a matrix that should:


1.   Displays **shape**, **size**, and **rank** of the matrix
2.   Displays whether the matrix is a ```square``` or ```non-square```
3. Displays whether the matrix is an **empty matrix**
4. Displays if the matrix is an ```identity```, ```ones```, or ```zero``` matrix




In [ ]:
## Function Area
def mat_desc(matrix):
  if matrix.size > 0:
    matrix = np.array(matrix)
    square_check = True if matrix.shape[0] == matrix.shape[1] else False
    ones_check = True if (np.ones([matrix.shape[0], matrix.shape[1]]) == matrix).all() else False
    zeroes_check = True if (np.zeros([matrix.shape[0], matrix.shape[1]]) == matrix).all() else False
    if matrix.shape[0] == matrix.shape[1]:
      identity_check = True if (np.identity(matrix.shape[0]) == matrix).all() else False
    else:
      identity_check = False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare: {square_check}\nIdentity: {identity_check}\nOnes: {ones_check}\nZeros: {zeroes_check}\n')
  else:
    print('Empty Matrix')

In [ ]:
## Matrix Declarations
ident = np.eye(4)
onces = np.ones((3,5))
rect = np.array([
       [3, 6, 8, 5],
       [1, 2, 9, 3],
       [11, 16, 7, 4]
])
zeroes = np.zeros((5,3))
nothing = np.array([])


In [ ]:
## Test Areas
print("1)")
mat_desc(ident)

print("2)")
mat_desc(onces)

print("3)")
mat_desc(rect)

print("4)")
mat_desc(zeroes)

print("5)")
mat_desc(nothing)

1)
Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Shape:	(4, 4)
Rank:	2
Square: True
Identity: True
Ones: False
Zeros: False

2)
Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Shape:	(3, 5)
Rank:	2
Square: False
Identity: False
Ones: True
Zeros: False

3)
Matrix:
[[ 3  6  8  5]
 [ 1  2  9  3]
 [11 16  7  4]]

Shape:	(3, 4)
Rank:	2
Square: False
Identity: False
Ones: False
Zeros: False

4)
Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(5, 3)
Rank:	2
Square: False
Identity: False
Ones: False
Zeros: True

5)
Empty Matrix


#***TASK 2***
Create a funciton named ```mat_operations()``` that takes two matrices a input parameters it should:


1.   Determine if the matrices are viable for operation and returns your own *error mesage* if they are not viable.
2.   Returns the **sum** of the matrices
3. Returns the **difference** of the matrices
4. Returns the **element-wise multiplication** of the matrices.
5. Returns the **element-wise division** of the matrices.



In [ ]:
## Function Area
def mat_operations(matrix1, matrix2):
  if matrix1.size and matrix2.size > 0:
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    viable_check = True if matrix1.shape[0] == matrix2.shape[0] and matrix1.shape[1] == matrix2.shape[1] else False
    if viable_check == False:
      print(f'Matrix 1:\n{matrix1}\n\nMatrix 2:\n{matrix2}\n\nMatrices Shapes: {matrix1.shape} and {matrix2.shape}\nViable for Operation: {viable_check}\nMatrices Not Viable for Operations: Inequal Matrix Shapes')
    else:
      sum_check = matrix1 + matrix2
      diff_check = matrix1 - matrix2
      mult_check = np.multiply(matrix1,matrix2)
      div_check = matrix1 / matrix2
      print(f'Matrix 1:\n{matrix1}\n\nMatrix 2:\n{matrix2}\n\nMatrices Shapes: {matrix1.shape} and {matrix2.shape}\nViable for Operation: {viable_check}\n\nSum of Matrices:\n{sum_check}\n\nDifference of Matrices:\n{diff_check}\n\nElement-Wise Multiplication:\n{mult_check}\n\nElement-Wise Division:\n{div_check}')
  else:
    print('Error: One or both of the matrices is/are null matrices')

In [ ]:
## Matrix Declarations
nullm = np.array([])
none = np.ones((5, 7))

one = np.eye(4)
two = np.array([
      [5, 3, 8, 9],
      [2, 3, 6, 1],
      [6, 7, 4, 5],
      [11, 9, 14, 7]
])

box1 = np.array([
       [8, 9, 2, 6, 3, 6],
       [9, 4, 4, 3, 4, 6],
       [6, 8, 7, 2, 5, 6],
])
box2 = np.array([
       [6, 3, 7, 4, 7, 1],
       [9, 6, 8, 6, 4, 5],
       [1, 5, 6, 4, 8, 3]
])

mat1 = np.eye(5)
mat2 = np.ones((4,5))

cat = np.eye(7)
dog = np.ones((7,7))

In [ ]:
## Test Area
print("1)")
mat_operations(nullm, none)
print('\n\n')

print("2)")
mat_operations(one, two)
print('\n\n')

print("3)")
mat_operations(box1, box2)
print('\n\n')

print("4)")
mat_operations(mat1, mat2)
print('\n\n')

print("5)")
mat_operations(cat, dog)

1)
Error: One or both of the matrices is/are null matrices



2)
Matrix 1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matrix 2:
[[ 5  3  8  9]
 [ 2  3  6  1]
 [ 6  7  4  5]
 [11  9 14  7]]

Matrices Shapes: (4, 4) and (4, 4)
Viable for Operation: True

Sum of Matrices:
[[ 6.  3.  8.  9.]
 [ 2.  4.  6.  1.]
 [ 6.  7.  5.  5.]
 [11.  9. 14.  8.]]

Difference of Matrices:
[[ -4.  -3.  -8.  -9.]
 [ -2.  -2.  -6.  -1.]
 [ -6.  -7.  -3.  -5.]
 [-11.  -9. -14.  -6.]]

Element-Wise Multiplication:
[[5. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 7.]]

Element-Wise Division:
[[0.2        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.14285714]]



3)
Matrix 1:
[[8 9 2 6 3 6]
 [9 4 4 3 4 6]
 [6 8 7 2 5 6]]

Matrix 2:
[[6 3 7 4 7 1]
 [9 6 8 6 4 5]
 [1 5 6 4 8 3]]

Matrices Shapes: (3, 6) and (3, 6)
Viable for Operation: True

Sum of Matrices:
[[14 12  9 1