<a href="https://colab.research.google.com/github/ja-nana/Linear-Algebra_ChE_2nd-Sem-2021/blob/main/Assignment_5_Siena_Vertudes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LABORATORY 6:
##**MATRIX OPERATIONS**
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

---
##Transposition
Transpose of matrix is done by flipping the values of its elements over diagonals. Both the rows and the columns from the original are switched:

*Example*

```
```
$$
A = \begin{bmatrix} 3 & 4 & 1\\ 9 & 8 & 7\\ 0 & -1 & 3\end{bmatrix} 
$$

```
```
$$
A^T = \begin{bmatrix} 3 & 9 & 0\\ 4 & 8 & -1\\ 1 & 7 & 3\end{bmatrix}
$$

```
```
---


This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [2]:
A = np.array([[1,2,4], [5,8,6],[9,5,3]])
A

array([[1, 2, 4],
       [5, 8, 6],
       [9, 5, 3]])

In [3]:
AT = np.transpose(A)
AT

array([[1, 5, 9],
       [2, 8, 5],
       [4, 6, 3]])

In [4]:
ATT = A.T
ATT

array([[1, 5, 9],
       [2, 8, 5],
       [4, 6, 3]])

In [5]:
np.array_equiv(AT,ATT)

True

---
## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices X and Y :

$$X = \begin{bmatrix} X_{(0,0)} & X_{(0,1)} \\ X_{(1,0)} & X_{(1,1)} \end{bmatrix} \\
$$
$$Y = \begin{bmatrix} Y_{(0,0)} & Y_{(0,1)} \\ Y_{(1,0)} & Y_{(1,1)} \end{bmatrix} \\
$$

The dot product will then be computed as:



$$X · Y = \begin{bmatrix} X_{(0,0)} * Y_{(0,1)} + X_{(0,1)} * Y_{(1,0)} & X_{(0,0)} * Y_{(0,1)} + X_{(0,1)} * Y_{(1,1)}\\ X_{(1,0)} * Y_{(0,0)} + X_{(1,1)} * Y_{(1,0)} & X_{(1,0)} * Y_{(0,1)} + X_{(1,1)} * Y_{(1,1)} \end{bmatrix} \\
$$

So if we assign values to *X* and *Y*:

$$X = \begin{bmatrix} 1 & 2 \\0 & 1 \end{bmatrix}, Y = \begin{bmatrix} -1 & 0 \\2 & 2\end{bmatrix} \\
$$

$$X · Y = \begin{bmatrix} 1 * -1 + 2 * 2 & 1 * 0 + 2 * 2\\ 0 * -1 + 1 * 2 & 0 * 0 + 1 * 2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\ 2 & 2 \end{bmatrix} \\
$$

This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [6]:
X = np.array([
    [1,20],
    [36,1]
])
Y = np.array([
    [-1,0],
    [2,7]
])

In [7]:
np.array_equiv(X, Y)

False

In [8]:
np.dot(X,Y)

array([[ 39, 140],
       [-34,   7]])

In [9]:
X.dot(Y)

array([[ 39, 140],
       [-34,   7]])

In [11]:
X @ Y

array([[ 39, 140],
       [-34,   7]])

In [10]:
np.matmul(X,Y)

array([[ 39, 140],
       [-34,   7]])

In [12]:
D = np.array([
    [4,2,2],
    [7,1,3],
    [5,4,2]
])
E = np.array([
    [-22,0,57],
    [29,4,66],
    [7,47,3]
])

In [13]:
D @ E

array([[ -16,  102,  366],
       [-104,  145,  474],
       [  20,  110,  555]])

In [14]:
D.dot(E)

array([[ -16,  102,  366],
       [-104,  145,  474],
       [  20,  110,  555]])

In [15]:
np.matmul(D, E)

array([[ -16,  102,  366],
       [-104,  145,  474],
       [  20,  110,  555]])

In [16]:
np.dot(D, E)

array([[ -16,  102,  366],
       [-104,  145,  474],
       [  20,  110,  555]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

**Rule 1: The inner dimensions of the two matrices in question must be the same.**

So given a matrix *A* with a shape of *(a,b)* where *a* and *b* are any integers. If we want to do a dot product between *A* and another matrix *B*, then matrix *B* should have a shape of *(b,c)* where *b* and *c* are any integers. So for given the following matrices:



$$X = \begin{bmatrix} 1 & 2 \\0 & 1 \\ 2 & 4\end{bmatrix}, Y = \begin{bmatrix} -1 & 0 \\2 & 2\\ 5 & 6\end{bmatrix} \\ Z=\begin{bmatrix} 3 & 4 & 1 \\ 2 & 6 & 4 \end{bmatrix}
$$

So in this case *A* has a shape of *(3,2)*, *B* has a shape of *(3,2)* and *C* has a shape of *(2,3)*. So the only matrix pairs that is eligible to perform dot product is matrices *A·C*, or *B·C*.

In [17]:
A = np.array([
    [21, 14],
    [15, -92],
    [30, 12]
])
B = np.array([
    [41,12],
    [31,37],
    [-41,-52]
])
C = np.array([
    [56,12,61],
    [21,81,52]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [18]:
A @ C

array([[ 1470,  1386,  2009],
       [-1092, -7272, -3869],
       [ 1932,  1332,  2454]])

In [19]:
B @ C

array([[ 2548,  1464,  3125],
       [ 2513,  3369,  3815],
       [-3388, -4704, -5205]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix *A* with a shape of *(a,b)* and matrix *B* with a shape of *(b,c)*, *A·B* should have a shape *(a,c)*.

In [20]:
A @ B.T

array([[ 1029,  1169, -1589],
       [ -489, -2939,  4169],
       [ 1374,  1374, -1854]])

In [21]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [22]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [23]:
X @ Y.T

array([[13]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

##**Rule 2: Dot Product has special properties**

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:

1.   A·B =/= B·A
2.   A·(B·C) = (A·B)·C
3.   A·(B+C) = A·B + A·C
4.   (B+C)·A = B·A + C·A
5.   A·I = A
6.   A·Φ=Φ






In [31]:
A = np.array([
    [1,2,1],
    [6,7,2],
    [5,1,9]
])
B = np.array([
    [5,1,8],
    [7,2,7],
    [1,5,3]
])
C = np.array([
    [6,2,0],
    [2,7,1],
    [9,8,3]
])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
A.dot(np.eye(3))

array([[1., 2., 1.],
       [6., 7., 2.],
       [5., 1., 9.]])

In [33]:
np.array_equal(A@B, B@A)

False

In [34]:
E = A @ (B @ C)
E

array([[ 365,  310,   85],
       [1473, 1196,  339],
       [1016, 1038,  274]])

In [35]:
F = (A @ B) @ C
F

array([[ 365,  310,   85],
       [1473, 1196,  339],
       [1016, 1038,  274]])

In [30]:
np.array_equal(E, X)

False

In [36]:
np.array_equiv(E, F)

True

In [37]:
A @ E

array([[ 4327,  3740,  1037],
       [14533, 12308,  3431],
       [12442, 12088,  3230]])

In [38]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.array_equal(a_dot_z,z_mat)

True

In [41]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##**Determinant**

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix *A* is denoted as *det(A)* or *|A|*. So let's say  *A* is represented as:

$$A = \begin{bmatrix} a_{(0,0)} & a_{(0,1)} \\a_{(1,0)} & a_{(1,1)} \end{bmatrix}
$$

We can compute for the determinant as:


$
|A| = a_{(0,0)} * a_{(1,1)} - a_{(1,0)} * a_{(0,1)}
$

So if we have *A* as:

$$A = \begin{bmatrix} 3 & 0 \\4 & 1 \end{bmatrix} , |A| = 3
$$

But you might wonder how about square matrices beyond the shape *(2,2)*? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [42]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [43]:
B = np.array([
              [1, 5, 2],
              [3, -1 ,-1],
              [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

In [44]:

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

***Inverse***

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix *M*:

$$M = \begin{bmatrix} 5 & -3 \\7 & 1 \end{bmatrix} 
$$

First, we need to get the determinant of *M*.

|M| = (5)(1) - (7)(-3) = 26

Next, we need to reform the matrix into the inverse form:

$
M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\-m_{(1,0)} & m_{(0,0)} \end{bmatrix}
$

So that will be:

$
M^{-1} = \frac{1}{26} \begin{bmatrix} 1 & 3 \\-7 & 5 \end{bmatrix} = \begin{bmatrix} \frac{1}{26} & \frac{3}{26} \\\frac{-7}{26} & \frac{5}{26} \end{bmatrix}
$

For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [45]:
M = np.array([
    [12,71],
    [-36, 54]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[0, 0],
       [0, 1]])

In [46]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [47]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [48]:
N = np.array([
    [8,23,63,11,9,3,15],
    [1,5,9,1,62,44,22],
    [5,4,2,0,10,10,8],
    [1,6,5,4,9,43,10],
    [81,4,85,17,78,15,10],
    [-15,5,2,80,10,6,-30],
    [-25,-15,19,27,10,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix *M*:

$
M \cdotp M^{-1} = I
$

In [49]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

##**Activity**

#####**Task 1**

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than *(3,3)*. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

First Property

A·B =/= B·A


In [50]:
X1 = np.array([
    [420,500,612],
    [745,877,998],
    [312,253,188]
])
Y1 = np.array([
    [1100,5245,8007],
    [1129,9769, 2003],
    [4454,7123,6578]
])
Z1 = np.array([
    [1235,1223,117],
    [2001,736,911],
    [275,600,4678]
])

In [51]:
X1@Y1

array([[ 3752348, 11446676,  8390176],
       [ 6254725, 19583692, 14286690],
       [ 1466189,  5447121,  4241607]])

In [52]:
Y1@X1

array([[ 6867709,  7175636,  7413026],
       [ 8377021,  9638672, 10816974],
       [ 9229651, 10138105, 11071266]])

In [53]:
np.array_equal(X1@Y1, Y1@X1)

False

Second Property

A·(B·C) = (A·B)·C

In [54]:
X2 = np.array([
    [320,510,812],
    [765,871,908],
    [372,153,138]
])
Y2 = np.array([
    [1680,1565,8024],
    [2399,1269, 2113],
    [7845,1029,7459]
])
Z2 = np.array([
    [3819,123,1217],
    [201,7365,9111],
    [8775,699,4599]
])

In [55]:
X2 @ (Y2 @ Z2)

array([[116587066458,  22390609242,  72587302410],
       [170187323172,  35442034032, 110109449074],
       [ 46169628687,  10050698367,  30840229359]])

In [56]:
(X2 @ Y2) @ Z2

array([[116587066458,  22390609242,  72587302410],
       [170187323172,  35442034032, 110109449074],
       [ 46169628687,  10050698367,  30840229359]])

In [57]:
np.array_equal(X2 @ (Y2 @ Z2), (X2 @ Y2) @ Z2)

True

Third Property

A·(B+C) = A·B + A·C


In [58]:
X3 = np.array([
    [3210,53410,9812],
    [7765,8712,9808],
    [3372,9153,5138]
])
Y3 = np.array([
    [80,15,24],
    [39,26, 23],
    [75,29,45]
])
Z3 = np.array([
    [819,1623,117],
    [791,1265,671],
    [715,6299,459]
])

In [59]:
X3 @ (Y3 + Z3)

array([[ 54967570, 136300626,  42464398],
       [ 21960015,  86031286,  12084225],
       [ 14687438,  49853123,   9417186]])

In [60]:
(X3 @ Y3) + (X3 @ Z3)

array([[ 54967570, 136300626,  42464398],
       [ 21960015,  86031286,  12084225],
       [ 14687438,  49853123,   9417186]])

In [61]:
np.array_equal(X3 @ (Y3 + Z3), (X3 @ Y3) + (X3 @ Z3))

True

Fourth Property

(B+C)·A = B·A + C·A


In [62]:
fourth_a = np.array([
          [34, 62, 12, 58],
          [77, 32, 25, 16],
          [21, 43, 14, 53]
])
fourth_b = np.array([
          [15, 33, 85],
          [19, 20, 41],
          [47, 23, 11],
          [24, 52, 30]
])
fourth_c = np.array([
          [86, 49, 80],
          [46, 62, 22],
          [37, 69, 5],
          [66, 24, 40]
])

In [63]:
fourth_bc = fourth_b + fourth_c
fourth_bc

array([[101,  82, 165],
       [ 65,  82,  63],
       [ 84,  92,  16],
       [ 90,  76,  70]])

In [64]:
fourth_left = np.dot(fourth_bc,fourth_a)
fourth_left

array([[13213, 15981,  5572, 15915],
       [ 9847,  9363,  3712,  8421],
       [10276,  8840,  3532,  7192],
       [10382, 11022,  3960, 10146]])

In [65]:
fourth_ba = np.dot(fourth_b,fourth_a)
fourth_ba

array([[4836, 5641, 2195, 5903],
       [3047, 3581, 1302, 3595],
       [3600, 4123, 1293, 3677],
       [5450, 4442, 2008, 3814]])

In [66]:
fourth_ca = np.dot(fourth_c,fourth_a)
fourth_ca

array([[ 8377, 10340,  3377, 10012],
       [ 6800,  5782,  2410,  4826],
       [ 6676,  4717,  2239,  3515],
       [ 4932,  6580,  1952,  6332]])

In [67]:
fourth_right = fourth_ba + fourth_ca
fourth_right

array([[13213, 15981,  5572, 15915],
       [ 9847,  9363,  3712,  8421],
       [10276,  8840,  3532,  7192],
       [10382, 11022,  3960, 10146]])

In [68]:
np.array_equiv(fourth_left, fourth_right)

True

Fifth Property

A·I = A


In [69]:
fifth_a = np.array([
          [30, 48, 75, 57],
          [28, 54, 40, 69],
          [59, 72, 38, 48],
          [53, 39, 73, 42]
])
fifth_i = np.eye(4)

In [70]:
fifth_left = fifth_a.dot(fifth_i)
fifth_left

array([[30., 48., 75., 57.],
       [28., 54., 40., 69.],
       [59., 72., 38., 48.],
       [53., 39., 73., 42.]])

In [71]:
np.array_equiv(fifth_left,fifth_a)

True

Sixth Property

A·Φ=Φ

In [72]:
sixth_a = np.array([
          [30, 48, 75, 57],
          [28, 54, 40, 69],
          [59, 72, 38, 48],
          [53, 39, 73, 42]
])
sixth_zero = np.zeros([4,4])

In [73]:
sixth_left = sixth_a.dot(sixth_zero)
sixth_left

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.array_equiv(sixth_left,sixth_zero)

True

##**Conclusion**

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity.